name: dotenv_gen_runner
description: Code generator for dotenv_gen
version: 0.0.3
homepage: https://github.com/North101/dotenv_gen
repository: https://github.com/North101/dotenv_gen
publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  analyzer: ^5.13.0
  build: ^2.4.0
  collection: ^1.17.1
  dotenv: ^4.1.0
  dotenv_gen:
    git:
      url: https://github.com/tomassasovsky/dotenv_gen.git
      path: dotenv_gen
  encrypt: ^5.0.1
  source_gen: ^1.3.2
  source_helper: ^1.3.3

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.1
  test: ^1.24.3

flutter:
